{
  "compatibilityLevel": 1568,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1052.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Power Query Code\",\"Power Query Code Transformed\",\"DMV_M_Discover_Dependency_Query\",\"DMV_M_Expression_Query\",\"Workspace_Name\",\"M Expressions Not Loaded into Dataset\",\"M Expressions Visible in Dataset\",\"Workspace_Server_Settings_URL\",\"Semantic_Model_Name\",\"Is_Dev\",\"Azure_Open_API_URL\",\"Azure_Open_API_Key\",\"Comment_Prompt_Template\",\"Variable_Rename_Suggestion_Template\",\"fnBulkReplace\",\"fnPromptAzureOpenAI\",\"fnGetComment\",\"fnGetCommentVariableSuggestion\",\"M Expressions Parsed Commenting\",\"M Expressions Variable Naming\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "DMV_M_Discover_Dependency_Query",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "select * from $SYSTEM.DISCOVER_M_EXPRESSIONS",
        "expression": [
          "let",
          "     // This code is selecting all records from a system catalog view, DISCOVER_CALC_DEPENDENCY, which holds information about dependencies between calculation entities.",
          "    #\"Selected All From System Discover Calc Dependency Table-1\" = \"select * from $SYSTEM.DISCOVER_CALC_DEPENDENCY\"",
          "in",
          "    #\"Selected All From System Discover Calc Dependency Table-1\""
        ],
        "kind": "m",
        "lineageTag": "38c71d34-f94e-4715-b7b8-6c61adcc692a",
        "queryGroup": "Dynamic Management View Queries "
      },
      {
        "name": "DMV_M_Expression_Query",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "select * from $SYSTEM.DISCOVER_M_EXPRESSIONS",
        "expression": [
          "let",
          "     // This code fetches all data from the system view DISCOVER_M_EXPRESSIONS. The system view contains metadata about all the expressions used in the Power BI model.",
          "    #\"Selected All From System Expressions-1\" = \"select * from $SYSTEM.DISCOVER_M_EXPRESSIONS\"",
          "in",
          "    #\"Selected All From System Expressions-1\""
        ],
        "kind": "m",
        "lineageTag": "03197deb-a94f-4644-a9a2-6f9a91fb0365",
        "queryGroup": "Dynamic Management View Queries "
      },
      {
        "name": "Workspace_Name",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "     // This line of code sets the variable \"Source\" to the value of \"Workspace_Server_Settings_URL\". It is part of a Power Query script to retrieve data from the specified URL.",
          "  #\"Retrieved_Workspace_Server_Settings_URL-1\" = Workspace_Server_Settings_URL,",
          "     // This line of code is transforming the source data into a structured table. \"Converted to Table\" is the title given to the new table that is created.```",
          "  #\"Created Single Row Table From Source-2\" = #table(1, {{#\"Retrieved_Workspace_Server_Settings_URL-1\"}}),",
          "     // This code transforms the 'Column1' data to text type, then splits this column based on the delimiter '/'. The result is two new columns named 'Column1.1' and 'Column1.2'.",
          "  #\"Split and Transformed Column Types-3\" = Table.SplitColumn(Table.TransformColumnTypes(#\"Created Single Row Table From Source-2\", {{\"Column1\", type text}}), \"Column1\", Splitter.SplitTextByEachDelimiter({\"/\"}, QuoteStyle.Csv, true), {\"Column1.1\", \"Column1.2\"}),",
          "     // This code is performing a transformation on the \"Column1.2\" of the \"Split column by delimiter\" table. It applies the Text.Clean function to each cell of the column to remove non-printable characters and changes the column's type to nullable text.",
          "  #\"Transformed and Cleaned Column-4\" = Table.TransformColumns(#\"Split and Transformed Column Types-3\", {{\"Column1.2\", each Text.Clean(_), type nullable text}}),",
          "     // This code is selecting the first row (index 0) of the 'Column1.2' from the table named 'Cleaned text' in Power Query.",
          "  #\"Extracted First Row From Cleaned Text Column-5\" = #\"Transformed and Cleaned Column-4\"{0}[Column1.2],",
          "     // This code is taking the output, #\"Extracted First Row From Cleaned Text Column-5\", from a previous operation and converting it into a table format using the Table.FromValue function.",
          "  #\"Transformed Drill Down into Table-6\" = Table.FromValue(#\"Extracted First Row From Cleaned Text Column-5\")",
          "in",
          "  #\"Transformed Drill Down into Table-6\""
        ],
        "kind": "m",
        "lineageTag": "3162a9e1-bb62-4af2-a459-75843a39a214",
        "queryGroup": "Dynamic Management View Queries "
      },
      {
        "name": "M Expressions Not Loaded into Dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "/*let",
          "  Source = AnalysisServices.Database(Workspace_Server_Settings_URL, Semantic_Model_Name, [Query = DMV_M_Expression_Query]),",
          "  #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"NAME\", \"Table Name\"}, {\"EXPRESSION\", \"M Expression\"}}),",
          "  #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns\", {\"M Expression\", \"Table Name\"}),",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Other Columns\", {\"Table Name\", \"M Expression\"}),",
          "  #\"Added Custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Reordered Columns\", \"Starts with Let\", each Text.StartsWith([M Expression], \"let\")), {{\"Starts with Let\", type logical}}),",
          "  #\"Added Dataset Name\" = Table.TransformColumnTypes(Table.AddColumn(#\"Added Custom\", \"Dataset Name\", each Table.First(Workspace_Name)[Value]), {{\"Dataset Name\", type text}})",
          "in",
          "  #\"Added Dataset Name\"*/",
          "",
          "  let",
          "     // This code is establishing a connection to an Analysis Services database using the specified server URL and semantic model name. It also prepares to run a specified DMV (Dynamic Management View) expression query.",
          "  #\"Extracted Analysis Services Database Info-1\" = AnalysisServices.Database(Workspace_Server_Settings_URL, Semantic_Model_Name, [Query = DMV_M_Expression_Query]),",
          "     // This code is renaming the 'NAME' column to 'Table Name' and the 'EXPRESSION' column to 'M Expression' in the 'Source' table.",
          "  #\"Columns Renamed in Source Table-2\" = Table.RenameColumns(#\"Extracted Analysis Services Database Info-1\", {{\"NAME\", \"Table Name\"}, {\"EXPRESSION\", \"M Expression\"}}),",
          "     // This code removes all columns from the table named #\"Columns Renamed in Source Table-2\", except for the columns \"M Expression\" and \"Table Name\".```",
          "  #\"Selected Specific Columns from Renamed Table-3\" = Table.SelectColumns(#\"Columns Renamed in Source Table-2\", {\"M Expression\", \"Table Name\"}),",
          "     // This code snippet is reordering the columns of a table. It removes other columns and specifies that \"Table Name\" and \"M Expression\" should be the first ones.",
          "  #\"Reordered Columns in Table-4\" = Table.ReorderColumns(#\"Selected Specific Columns from Renamed Table-3\", {\"Table Name\", \"M Expression\"}),",
          "     // This code adds a new column called \"Starts with Let\" to the \"Reordered Columns\" table, which checks if each data row of the [M Expression] column starts with the word \"let\". The result of this operation is then transformed into a logical data type.",
          "  #\"Added and Transformed Column to Check for Let Start-5\" = Table.TransformColumnTypes(Table.AddColumn(#\"Reordered Columns in Table-4\", \"Starts with Let\", each Text.StartsWith([M Expression], \"let\")), {{\"Starts with Let\", type logical}}),",
          "     // This piece of code is adding a new column named \"Dataset Name\" to the table. It populates this new column with the first value from the 'Workspace_Name' table. After that, it transforms the data type of the 'Dataset Name' column to 'text'.```",
          "  #\"Transformed Column Types and Added Dataset Name-6\" = Table.TransformColumnTypes(Table.AddColumn(#\"Added and Transformed Column to Check for Let Start-5\", \"Dataset Name\", each Table.First(Workspace_Name)[Value]), {{\"Dataset Name\", type text}})",
          "in",
          "  #\"Transformed Column Types and Added Dataset Name-6\""
        ],
        "kind": "m",
        "lineageTag": "fe705c67-7384-449f-9018-0504be949e27",
        "queryGroup": "Dynamic Management View Queries "
      },
      {
        "name": "M Expressions Visible in Dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "/*let",
          "  #\"Source\" = AnalysisServices.Database(Workspace_Server_Settings_URL, Semantic_Model_Name, [Query = DMV_M_Discover_Dependency_Query]),",
          "    #\"Filter by Partition\" = Table.SelectRows(#\"Source\", each ([OBJECT_TYPE] = \"PARTITION\")),",
          "    #\"Filter out empty Tables\" = Table.SelectRows(#\"Filter by Partition\", each [TABLE] <> null and [TABLE] <> \"\"),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filter out empty Tables\",{\"EXPRESSION\", \"TABLE\"}),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Other Columns\",{\"TABLE\", \"EXPRESSION\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"TABLE\", \"Table Name\"}, {\"EXPRESSION\", \"M Expression\"}}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Renamed Columns\",{{\"Table Name\", Order.Ascending}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Sorted Rows\", {\"Table Name\"}),",
          "  #\"Added Dataset Name\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed Duplicates\", \"Dataset Name\", each Table.First(Workspace_Name)[Value]), {{\"Dataset Name\", type text}})",
          "in",
          "    #\"Added Dataset Name\"*/",
          "let",
          "     // This code is establishing a connection to an Analysis Services database using a specified server URL, semantic model name, and a data management view (DMV) query for discovering dependencies.",
          "    #\"Executed_AnalysisServices_Database_Query-1\" = AnalysisServices.Database(Workspace_Server_Settings_URL, Semantic_Model_Name, [Query = DMV_M_Discover_Dependency_Query]),",
          "     // This code is filtering the rows in the \"Source\" table, selecting only the ones where the \"OBJECT_TYPE\" is equal to \"PARTITION\".",
          "    #\"Selected Partition Type Rows-2\" = Table.SelectRows(#\"Executed_AnalysisServices_Database_Query-1\", each ([OBJECT_TYPE] = \"PARTITION\")),",
          "     // ```This code is filtering out rows from the \"Filter by Partition\" table where the \"TABLE\" column is either null or an empty string.```",
          "    #\"Filtered Rows With Non-Empty Table Names-3\" = Table.SelectRows(#\"Selected Partition Type Rows-2\", each [TABLE] <> null and [TABLE] <> \"\"),",
          "     // This code is selecting only the 'EXPRESSION' and 'TABLE' columns from the table \"Filter out empty Tables\" and removes the rest of the columns.",
          "    #\"Selected Expression and Table Columns-4\" = Table.SelectColumns(#\"Filtered Rows With Non-Empty Table Names-3\",{\"EXPRESSION\", \"TABLE\"}),",
          "     // This code is reordering the columns in the table named #\"Selected Expression and Table Columns-4\". It sets the order to the columns \"TABLE\" and then \"EXPRESSION\".",
          "    #\"Reordered Columns in Table-5\" = Table.ReorderColumns(#\"Selected Expression and Table Columns-4\",{\"TABLE\", \"EXPRESSION\"}),",
          "     // ```This code is renaming the columns of a table. Specifically, it changes the column name \"TABLE\" to \"Table Name\" and changes \"EXPRESSION\" to \"M Expression\".```",
          "    #\"Renamed Table and Expression Columns-6\" = Table.RenameColumns(#\"Reordered Columns in Table-5\",{{\"TABLE\", \"Table Name\"}, {\"EXPRESSION\", \"M Expression\"}}),",
          "     // This code is sorting the rows in the table named \"Renamed Columns\" in ascending order based on the column \"Table Name\".",
          "    #\"Sorted Table By Name Ascending-7\" = Table.Sort(#\"Renamed Table and Expression Columns-6\",{{\"Table Name\", Order.Ascending}}),",
          "     // This line of code removes the duplicate rows in the column \"Table Name\" from the \"Sorted Rows\" table.",
          "    #\"Removed Duplicate Table Names-8\" = Table.Distinct(#\"Sorted Table By Name Ascending-7\", {\"Table Name\"}),",
          "     // This code adds a new column labeled \"Dataset Name\" to the table \"Removed Duplicates\". It populates this column with the first value from the \"Workspace_Name\" table. The new column's data type is then set to text.",
          "  #\"Transformed Data Type and Added Dataset Name Column-9\" = Table.TransformColumnTypes(Table.AddColumn(#\"Removed Duplicate Table Names-8\", \"Dataset Name\", each Table.First(Workspace_Name)[Value]), {{\"Dataset Name\", type text}})",
          "in",
          "    #\"Transformed Data Type and Added Dataset Name Column-9\""
        ],
        "kind": "m",
        "lineageTag": "bf83a2df-47f6-4356-9f73-3ac55b985afb",
        "queryGroup": "Dynamic Management View Queries "
      },
      {
        "name": "Workspace_Server_Settings_URL",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "description": "The endpoint for the workspace as described in https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-connect-tools",
        "expression": [
          "// This code is establishing a connection to a Power BI dataset located at the specified URL. It also sets metadata indicating that this is a parameter query, it should be treated as text, and that it is required.",
          "\"powerbi://api.powerbi.com/v1.0/myorg/\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
        ],
        "kind": "m",
        "lineageTag": "dae7d153-a12b-4210-827a-41878367f0a4",
        "queryGroup": "Parameters\\Power Query"
      },
      {
        "name": "Semantic_Model_Name",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Name of the Semantic Model (aka Dataset) in the service.",
        "expression": "\"SampleModel\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d5a38e6d-7d23-425d-9932-1c51ed687f05",
        "queryGroup": "Parameters\\Power Query"
      },
      {
        "name": "Is_Dev",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Logical"
          }
        ],
        "expression": [
          "let",
          "    Source = false meta [IsParameterQuery=true, Type=\"Logical\", IsParameterQueryRequired=true]",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "942216c3-a56e-4a9f-97d3-375e94ff84e3",
        "queryGroup": "Parameters\\Power Query"
      },
      {
        "name": "Azure_Open_API_URL",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "The endpoint to the Azure OpenAI chat completions.",
        "expression": "\"XYZ\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c8b8297d-2e56-4125-84e4-91813653df7e",
        "queryGroup": "Parameters\\Azure Open AI"
      },
      {
        "name": "Azure_Open_API_Key",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "The API key to access your Azure OpenAI instance.",
        "expression": "\"XYZ\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "1e2f7e1b-a784-4545-b513-324a7fab8488",
        "queryGroup": "Parameters\\Azure Open AI"
      },
      {
        "name": "Comment_Prompt_Template",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": [
          "let",
          "    Source = \"You are an assistant to help Power Query developers comment their code.",
          "    Please take the code between the ``` marks and perform the following:",
          "    1) Return a comment explaining what that piece of code is doing.",
          "    2) Do not start the comment with the word Step or a number",
          "    3) Do not copy code into the comment.",
          "    4) Keep the comments to a maximum of 225 characters.",
          "    ```{_M_CODE_}```\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "0d2130b9-712c-47fe-8076-92d32e9c1a50",
        "queryGroup": "Azure Open AI"
      },
      {
        "name": "Variable_Rename_Suggestion_Template",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": [
          "let",
          "    Source = \"You are an assistant to help Power Query developers comment their code.",
          "    Please take the code between the ``` marks and perform the following:",
          "    1) Return a variable name explaining what that piece of code is doing.",
          "    2) The variable name should always start with a verb in the past tense.",
          "    3) The variable name should have spaces between words.",
          "    4) Please keep the variable to a maximum of 50 characters.",
          "    5) The variable name should be wrapped in double quotes.",
          "    ```{_M_CODE_}```\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "e5b5b9b9-8490-47fa-a420-fe241795d572",
        "queryGroup": "Azure Open AI"
      },
      {
        "name": "fnBulkReplace",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let BulkReplace = (ReplaceText as text, FindReplaceTable as table) =>",
          "    let",
          "    // Convert column value to Table",
          "    DataTable= Table.FromRecords({[Code = ReplaceText]}),",
          "    // Convert DataTable to list",
          "    DataTableColumn = Table.ToList(DataTable),",
          "    //Convert the FindReplaceTable to a list using the Table.ToRows function",
          "    //so we can reference the list with an index number",
          "    FindReplaceList = Table.ToRows(FindReplaceTable),",
          "    //Count number of rows in the FindReplaceTable to determine",
          "    //how many iterations are needed",
          "    Counter = Table.RowCount(FindReplaceTable),",
          "    //Define a function to iterate over our list",
          "    //with the Table.ReplaceValue function",
          "    BulkReplaceValues = (DataTableTemp, n) =>",
          "    let",
          "    //Replace values using nth item in FindReplaceList",
          "    ReplaceTable = Table.ReplaceValue(",
          "    DataTableTemp,",
          "    //replace null with empty string",
          "    if FindReplaceList{n}{0} = null then \"\" else FindReplaceList{n}{0},",
          "    if FindReplaceList{n}{1} = null then \"\" else FindReplaceList{n}{1},",
          "    Replacer.ReplaceText,",
          "    {\"Code\"}",
          "    )",
          "in",
          "    //if we are not at the end of the FindReplaceList",
          "    //then iterate through Table.ReplaceValue again",
          "    if n = Counter - 1",
          "    then ReplaceTable",
          "    else @BulkReplaceValues(ReplaceTable, n + 1),",
          "    //Evaluate the sub-function at the first row",
          "    Output = BulkReplaceValues(DataTable, 0)",
          "in",
          "    Table.First(Output)",
          "in",
          "    BulkReplace"
        ],
        "kind": "m",
        "lineageTag": "deb6844c-d5b0-418b-b2d1-38996976298e",
        "queryGroup": "Functions"
      },
      {
        "name": "fnPromptAzureOpenAI",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Prompt as text) =>",
          "    let",
          "    Url = #\"Azure_Open_API_URL\",",
          "    ApiKey = #\"Azure_Open_API_Key\",",
          "    Headers = [",
          "    #\"Content-Type\" = \"application/json\",",
          "    #\"api-key\" = ApiKey",
          "    ],",
          "    Body = Json.FromValue([messages = {[role=\"user\", content = Prompt]}]),",
          "    Response = Web.Contents (Url , [Headers=Headers, Content=Body]),",
          "    Content = Json.Document(Response)",
          "in",
          "    Content",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "8a266ea0-eacc-4c61-97f9-634a3ad9ca9e",
        "queryGroup": "Functions\\Azure Open API"
      },
      {
        "name": "fnGetComment",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Input as text) =>",
          "    let",
          "    Source = fnPromptAzureOpenAI(Input),",
          "    choices = Source[choices],",
          "    choices1 = choices{0},",
          "    message = choices1[message],",
          "    content = message[content]",
          "in",
          "    content",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "21182f75-ba63-4e51-8dc4-a4053b1831e6",
        "queryGroup": "Functions\\Azure Open API"
      },
      {
        "name": "fnGetCommentVariableSuggestion",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Input as text) =>",
          "    let",
          "    Source = fnPromptAzureOpenAI(Input),",
          "    choices = Source[choices],",
          "    choices1 = choices{0},",
          "    message = choices1[message],",
          "    content = message[content]",
          "in",
          "    content",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "fb7f8cb9-37ea-404a-8cc1-32161ce559cf",
        "queryGroup": "Functions\\Azure Open API"
      },
      {
        "name": "M Expressions Parsed Commenting",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "/*let",
          "    Source = #\"Power Query Code\",",
          "    #\"Split Column by Delimiter\" = Table.ExpandListColumn(Table.TransformColumns(Source, {{\"M Expression\", Splitter.SplitTextByDelimiter(\"#(lf)\", QuoteStyle.None), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), \"M Expression\"),",
          "    #\"Added Index\" = Table.AddIndexColumn(#\"Split Column by Delimiter\", \"Index\", 1, 1, Int64.Type),",
          "    #\"Grouped Rows\" = Table.Group(#\"Added Index\", {\"M Expression ID\"}, {{\"Count\", each _, type table[#\"M Expression ID\" = number, #\"Dataset ID\" = nullable text, #\"Dataset Name\" = nullable text, #\"Table Name\" = text, #\"M Expression\" = nullable text, #\"Starts with Let\" = any, Index = number]}}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Grouped Rows\", \"Custom\", each Table.AddIndexColumn([Count], \"Line Index\", 0, 1)),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\", {\"M Expression ID\", \"Count\"}),",
          "    #\"Expanded Custom\" = Table.ExpandTableColumn(#\"Removed Columns\", \"Custom\", {\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"Line Index\"}, {\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"Line Index\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Custom\", {{\"M Expression\", type text}}),",
          "    #\"Add Include For Comment\" = Table.AddColumn(#\"Changed Type\", \"Exclude For Comment\", each if Text.Contains([M Expression],\"=\") = false or Text.StartsWith(Text.Clean([M Expression]),\"let\") or Text.StartsWith(Text.Clean([M Expression]),\"in\") then true else false, type logical),",
          "    #\"Add M Expression To Comment\" = Table.AddColumn(#\"Add Include For Comment\", \"M Expression To Comment\", each if [Exclude For Comment] then null else Replacer.ReplaceText(Comment_Prompt_Template,\"{_M_CODE_}\",[M Expression])),",
          "    #\"Call fnGetComment\" = Table.AddColumn(#\"Add M Expression To Comment\", \"fnGetComment\", each if [Exclude For Comment] = false then fnGetComment([M Expression To Comment]) else null),",
          "    #\"Add M Expression with Comment\" = Table.AddColumn(#\"Call fnGetComment\", \"M Expression with Comment\", each if [Exclude For Comment] = true then [M Expression] else  \"     // \" & [fnGetComment] & \"#(lf)\" & [M Expression]),",
          "    #\"Transform columns\" = Table.TransformColumnTypes(#\"Add M Expression with Comment\", {{\"M Expression ID\", type text}, {\"Dataset ID\", type text}, {\"Dataset Name\", type text}, {\"Table Name\", type text}, {\"Starts with Let\", type text}, {\"Index\", type text}, {\"Line Index\", type text}, {\"M Expression To Comment\", type text}, {\"fnGetComment\", type text}, {\"M Expression with Comment\", type text}}),",
          "    #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"M Expression ID\", null}, {\"Dataset ID\", null}, {\"Dataset Name\", null}, {\"Table Name\", null}, {\"Starts with Let\", null}, {\"Index\", null}, {\"Line Index\", null}, {\"M Expression To Comment\", null}, {\"fnGetComment\", null}, {\"M Expression with Comment\", null}})",
          "in",
          "    #\"Replace errors\"*/",
          "let",
          "     // This line of code is assigning the content of \"Power Query Code\" to a new variable named \"Source\".",
          "    #\"Queried Power Code-1\" = #\"Power Query Code\",",
          "     // This code splits the 'M Expression' column of the 'Source' table into multiple rows at each linefeed (represented by '#(lf)'). The 'Table.TransformColumns' function is used to make this split, and the 'Table.ExpandListColumn' function expands the resulting lists into new rows.",
          "    #\"Expanded List Column From Transformed Text-2\" = Table.ExpandListColumn(Table.TransformColumns(#\"Queried Power Code-1\", {{\"M Expression\", Splitter.SplitTextByDelimiter(\"#(lf)\", QuoteStyle.None), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), \"M Expression\"),",
          "     // This code is adding an index column named \"Index\" to the data in the \"Split Column by Delimiter\" table. It begins at 1 and increments by 1 for each row, with the data type designated as Int64.",
          "    #\"Added Index Column to Split Delimiter Table-3\" = Table.AddIndexColumn(#\"Expanded List Column From Transformed Text-2\", \"Index\", 1, 1, Int64.Type),",
          "     // This code is grouping rows in the 'Added Index' table based on 'M Expression ID'. It then creates a new table with the grouping, while maintaining the original columns and data types.",
          "    #\"Grouped Table By M Expression ID-4\" = Table.Group(#\"Added Index Column to Split Delimiter Table-3\", {\"M Expression ID\"}, {{\"Count\", each _, type table[#\"M Expression ID\" = number, #\"Dataset ID\" = nullable text, #\"Dataset Name\" = nullable text, #\"Table Name\" = text, #\"M Expression\" = nullable text, #\"Starts with Let\" = any, Index = number]}}),",
          "     // This code is adding a new column called \"Custom\" to the \"Grouped Rows\" table. The values in this column come from adding an index column called \"Line Index\" to the \"Count\" table, starting at 0 and incrementing by 1.",
          "    #\"Added Index Column to Grouped Rows-5\" = Table.AddColumn(#\"Grouped Table By M Expression ID-4\", \"Custom\", each Table.AddIndexColumn([Count], \"Line Index\", 0, 1)),",
          "     // This code is removing the columns labeled \"M Expression ID\" and \"Count\" from the table referred to as \"Added Custom\".",
          "    #\"Removed Unnecessary Columns-6\" = Table.RemoveColumns(#\"Added Index Column to Grouped Rows-5\", {\"M Expression ID\", \"Count\"}),",
          "     // This code is expanding the \"Custom\" table column from the \"Removed Columns\" table. It takes originally nested information (\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", etc.) and displays it in separate, expanded columns.",
          "    #\"Expanded Table Column Properties-7\" = Table.ExpandTableColumn(#\"Removed Unnecessary Columns-6\", \"Custom\", {\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"Line Index\"}, {\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"Line Index\"}),",
          "     // This piece of code is transforming the column \"M Expression\" in the table #\"Expanded Table Column Properties-7\" to text data type.",
          "    #\"Transformed Column Type to Text-8\" = Table.TransformColumnTypes(#\"Expanded Table Column Properties-7\", {{\"M Expression\", type text}}),",
          "     // This code is adding a new column in the table, named \"Exclude For Comment\". This column will contain boolean values based on specific conditions. If the \"M Expression\" column does not contain an \"=\", or it starts with \"let\" or \"in\" after cleaning the text, it returns true; otherwise, it returns false.",
          "    #\"Added Exclusion Column for Comments-9\" = Table.AddColumn(#\"Transformed Column Type to Text-8\", \"Exclude For Comment\", each if Text.Contains([M Expression],\"=\") = false or Text.StartsWith(Text.Clean([M Expression]),\"let\") or Text.StartsWith(Text.Clean([M Expression]),\"in\") then true else false, type logical),",
          "     // The code is adding a new column, \"M Expression To Comment\", to the table. If the \"Exclude For Comment\" field is true, it assigns null to the new field. However, if it's false, it fills the field with the result of replacing \"{_M_CODE_}\" in \"Comment_Prompt_Template\" with the \"M Expression\" field.",
          "    #\"Added Conditional Column for M Expression Comment-10\" = Table.AddColumn(#\"Added Exclusion Column for Comments-9\", \"M Expression To Comment\", each if [Exclude For Comment] then null else Replacer.ReplaceText(Comment_Prompt_Template,\"{_M_CODE_}\",[M Expression])),",
          "     // This code is adding a new column named \"fnGetComment\" to the existing table. It uses the function \"fnGetComment\" to populate the cells in the new column, but only if the \"Exclude For Comment\" column for that row is set to false. If \"Exclude For Comment\" is true, it inserts null.",
          "    #\"Added Column With Comments For M Expression-11\" = Table.AddColumn(#\"Added Conditional Column for M Expression Comment-10\", \"fnGetComment\", each if [Exclude For Comment] = false then fnGetComment([M Expression To Comment]) else null),",
          "     // This code is adding a new column to the table \"Call fnGetComment\" named \"M Expression with Comment\". It checks if the current row should be excluded for a comment. If true, the value for the new column is populated from the \"M Expression\" column. If false, it inserts a new comment followed by the value from the \"M Expression\" column.",
          "    #\"Added Comment Column To Table-12\" = Table.AddColumn(#\"Added Column With Comments For M Expression-11\", \"M Expression with Comment\", each if [Exclude For Comment] = true then [M Expression] else  \"     // \" & [fnGetComment] & \"#(lf)\" & [M Expression]),",
          "    // This code removes line feeds with a space",
          "    #\"Replaced Line Feeds with Space-13\" = Table.ReplaceValue(#\"Added Comment Column To Table-12\",\"#(#)(lf)\",\" \",Replacer.ReplaceText,{\"fnGetComment\"}),",
          "     // This code is transforming the data types of multiple columns in the \"Add M Expression with Comment\" table to text type.",
          "    #\"Transformed Column Types in M Expression Table-14\" = Table.TransformColumnTypes( #\"Replaced Line Feeds with Space-13\" , {{\"M Expression ID\", type text}, {\"Dataset ID\", type text}, {\"Dataset Name\", type text}, {\"Table Name\", type text}, {\"Starts with Let\", type text}, {\"Index\", type text}, {\"Line Index\", type text}, {\"M Expression To Comment\", type text}, {\"fnGetComment\", type text}, {\"M Expression with Comment\", type text}}),",
          "     // This code is replacing any error values in designated columns of the 'Transform columns' table with null values using the Table.ReplaceErrorValues function in Power Query.",
          "    #\"Replaced Error Values with Null in Table Columns-15\" = Table.ReplaceErrorValues(#\"Transformed Column Types in M Expression Table-14\", {{\"M Expression ID\", null}, {\"Dataset ID\", null}, {\"Dataset Name\", null}, {\"Table Name\", null}, {\"Starts with Let\", null}, {\"Index\", null}, {\"Line Index\", null}, {\"M Expression To Comment\", null}, {\"fnGetComment\", null}, {\"M Expression with Comment\", null}})",
          "in",
          "    #\"Replaced Error Values with Null in Table Columns-15\""
        ],
        "kind": "m",
        "lineageTag": "67897e75-b8ae-4004-8b95-c6f75be4381b",
        "queryGroup": "Dynamic Management View Queries "
      },
      {
        "name": "M Expressions Variable Naming",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "/*let",
          "    Source = #\"Power Query Code\",",
          "    #\"Split Column by Delimiter\" = Table.ExpandListColumn(Table.TransformColumns(Source, {{\"M Expression\", Splitter.SplitTextByDelimiter(\"#(lf)\", QuoteStyle.None), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), \"M Expression\"),",
          "    #\"Added Index\" = Table.AddIndexColumn(#\"Split Column by Delimiter\", \"Index\", 1, 1, Int64.Type),",
          "    #\"Grouped Rows\" = Table.Group(#\"Added Index\", {\"M Expression ID\"}, {{\"Count\", each _, type table[#\"M Expression ID\" = number, #\"Dataset ID\" = nullable text, #\"Dataset Name\" = nullable text, #\"Table Name\" = text, #\"M Expression\" = nullable text, #\"Starts with Let\" = any, Index = number]}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Grouped Rows\", \"Custom\", each Table.AddIndexColumn([Count], \"Line Index\", 0, 1)),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom1\", {\"M Expression ID\", \"Count\"}),",
          "    #\"Expanded Custom\" = Table.ExpandTableColumn(#\"Removed Columns\", \"Custom\", {\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"Line Index\"}, {\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"Line Index\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Custom\", {{\"M Expression\", type text}}),",
          "    #\"Add M Expression after Equal Since\" = Table.AddColumn(#\"Changed Type\", \"M Expression after Equal Sign\", each if Text.Contains([M Expression],\"=\") = false then null else Text.Clean(Text.Trim(Text.AfterDelimiter([M Expression],\"=\")))),",
          "    #\"Add M Expression before Equal Sign\" = Table.AddColumn(#\"Add M Expression after Equal Since\", \"M Expression Before Equal Sign\", each if Text.Contains([M Expression],\"=\") = false then null else Text.Clean(Text.Trim(Text.BeforeDelimiter([M Expression],\"=\")))),",
          "    #\"Add Is Parameter\" = Table.TransformColumnTypes(Table.AddColumn(#\"Add M Expression before Equal Sign\", \"Is Parameter\", each Text.Contains([M Expression], \"meta [IsParameterQuery=true\")), {{\"Is Parameter\", type logical}}),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Add Is Parameter\", {\"Line Index\", \"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"M Expression after Equal Sign\", \"M Expression Before Equal Sign\"}),",
          "    #\"Add M Expression To Suggest Variable Name\" = Table.AddColumn(#\"Reordered Columns\", \"M Expression To Suggest Variable Name\", each if [M Expression after Equal Sign] = null or [Is Parameter] then null else Replacer.ReplaceText(Variable_Rename_Suggestion_Template,\"{_M_CODE_}\",[M Expression after Equal Sign])),",
          "    #\"Call fnGetCommentVariableSuggestion\" = Table.AddColumn(#\"Add M Expression To Suggest Variable Name\", \"fnGetCommentVariableSuggestion\", each if [M Expression To Suggest Variable Name] = null then null else fnGetCommentVariableSuggestion([M Expression To Suggest Variable Name])),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Call fnGetCommentVariableSuggestion\", \"Suggested Variable Name\", each if [fnGetCommentVariableSuggestion] = null then null else \"#\" & Text.Range([fnGetCommentVariableSuggestion],0,Text.Length([fnGetCommentVariableSuggestion])-1) & \"-\" & Number.ToText([Line Index]) & \"\"\"\"),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each [Suggested Variable Name] <> null and [Suggested Variable Name] <> \"\"),",
          "    #\"Remove other columns not needed\" = Table.SelectColumns(#\"Filtered Rows\", {\"M Expression Before Equal Sign\", \"Suggested Variable Name\", \"M Expression ID\"}),",
          "    #\"Standardized column names\" = Table.RenameColumns(#\"Remove other columns not needed\", {{\"M Expression Before Equal Sign\", \"Find\"}, {\"Suggested Variable Name\", \"Replace\"}}),",
          "    #\"Setup Column Types\" = Table.TransformColumnTypes(#\"Standardized column names\", {{\"Replace\", type text}, {\"Find\", type text}}),",
          "    #\"Transform columns\" = Table.TransformColumnTypes(#\"Setup Column Types\", {{\"M Expression ID\", type text}}),",
          "    #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"M Expression ID\", null}})",
          "in",
          "    #\"Replace errors\"*/",
          "let",
          "     // This line of code is assigning the content of \"Power Query Code\" to a new variable named \"Source\".",
          "    #\"Queried Power Code-1\" = #\"Power Query Code\",",
          "     // This code splits the 'M Expression' column of the 'Source' table into multiple rows at each linefeed (represented by '#(lf)'). The 'Table.TransformColumns' function is used to make this split, and the 'Table.ExpandListColumn' function expands the resulting lists into new rows.",
          "    #\"Expanded List Column From Transformed Text-2\" = Table.ExpandListColumn(Table.TransformColumns(#\"Queried Power Code-1\", {{\"M Expression\", Splitter.SplitTextByDelimiter(\"#(lf)\", QuoteStyle.None), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), \"M Expression\"),",
          "     // This code is adding an index column named \"Index\" to the data in the \"Split Column by Delimiter\" table. It begins at 1 and increments by 1 for each row, with the data type designated as Int64.",
          "    #\"Added Index Column to Split Delimiter Table-3\" = Table.AddIndexColumn(#\"Expanded List Column From Transformed Text-2\", \"Index\", 1, 1, Int64.Type),",
          "     // This code is grouping rows in the 'Added Index' table based on 'M Expression ID'. It then creates a new table with the grouping, while maintaining the original columns and data types.",
          "    #\"Grouped Table By M Expression ID-4\" = Table.Group(#\"Added Index Column to Split Delimiter Table-3\", {\"M Expression ID\"}, {{\"Count\", each _, type table[#\"M Expression ID\" = number, #\"Dataset ID\" = nullable text, #\"Dataset Name\" = nullable text, #\"Table Name\" = text, #\"M Expression\" = nullable text, #\"Starts with Let\" = any, Index = number]}}),",
          "     // This code is adding a new column named \"Custom\" to the \"Grouped Rows\" table. In this new column, it's applying an index to each item in the \"Count\" column, starting from 0 and incrementing by 1.",
          "    #\"Added Index Column to Grouped Rows-5\" = Table.AddColumn(#\"Grouped Table By M Expression ID-4\", \"Custom\", each Table.AddIndexColumn([Count], \"Line Index\", 0, 1)),",
          "     // This code is removing the columns \"M Expression ID\" and \"Count\" from the table labeled \"Added Custom1\".",
          "    #\"Removed Unnecessary Columns from Table-6\" = Table.RemoveColumns(#\"Added Index Column to Grouped Rows-5\", {\"M Expression ID\", \"Count\"}),",
          "     // This code is expanding the \"Custom\" table column from the \"Removed Columns\" table. It takes originally nested information (\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", etc.) and displays it in separate, expanded columns.",
          "    #\"Expanded Table Column Properties-7\" = Table.ExpandTableColumn(#\"Removed Unnecessary Columns from Table-6\", \"Custom\", {\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"Line Index\"}, {\"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"Line Index\"}),",
          "     // This piece of code is transforming the column \"M Expression\" in the table #\"Expanded Table Column Properties-7\" to text data type.",
          "    #\"Transformed Column Type to Text-8\" = Table.TransformColumnTypes(#\"Expanded Table Column Properties-7\", {{\"M Expression\", type text}}),",
          "     // This code adds a new column to the table \"Changed Type\" titled \"M Expression after Equal Sign\". If the \"M Expression\" in the row does not contain an equal sign, it places null in the new cell. If there's an equal sign, it extracts text after the equal sign, removes unnecessary spaces and writes it into the row of the new column.",
          "    #\"Extracted Equal Sign After M Expression-9\" = Table.AddColumn(#\"Transformed Column Type to Text-8\", \"M Expression after Equal Sign\", each if Text.Contains([M Expression],\"=\") = false then null else Text.Clean(Text.Trim(Text.AfterDelimiter([M Expression],\"=\")))),",
          "     // This piece of code is adding a new column to an existing table called \"Add M Expression after Equal Since\". The new column is titled \"M Expression Before Equal Sign\". This column will contain the cleaned and trimmed portion of a text string that occurs before the \"=\" sign in the M Expression column. It will return null if the \"=\" sign is not present.",
          "    #\"Split and Cleaned M Expression Before Equal Sign-10\" = Table.AddColumn(#\"Extracted Equal Sign After M Expression-9\", \"M Expression Before Equal Sign\", each if Text.Contains([M Expression],\"=\") = false then null else Text.Clean(Text.Trim(Text.BeforeDelimiter([M Expression],\"=\")))),",
          "     // This code is adding a new column named \"Is Parameter\" to the table. It checks if each \"M Expression\" contains the text \"meta [IsParameterQuery=true]\". The column type for \"Is Parameter\" is set as logical.",
          "    #\"Add Is Parameter\" = Table.TransformColumnTypes(Table.AddColumn(#\"Split and Cleaned M Expression Before Equal Sign-10\", \"Is Parameter\", each Text.Contains([M Expression], \"meta [IsParameterQuery=true\")), {{\"Is Parameter\", type logical}}),",
          "     // This code is reordering the columns in a table named \"Add Is Parameter\". The new order specified by column names is \"Line Index\", \"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"M Expression after Equal Sign\", \"M Expression Before Equal Sign\".",
          "    #\"Reordered Table Columns-12\" = Table.ReorderColumns(#\"Add Is Parameter\", {\"Line Index\", \"M Expression ID\", \"Dataset ID\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\", \"Index\", \"M Expression after Equal Sign\", \"M Expression Before Equal Sign\"}),",
          "     // This code is adding a new column named \"M Expression To Suggest Variable Name\" to the table \"Reordered Columns\". If the \"M Expression after Equal Sign\" column is null or if the \"Is Parameter\" column is true, it populates the new column with null. Otherwise, it replaces the text \"{_M_CODE_}\" in the \"Variable_Rename_Suggestion_Template\" with the corresponding value from the \"M Expression after Equal Sign\" column.",
          "    #\"Added Column with Suggested Variable Names-13\" = Table.AddColumn(#\"Reordered Table Columns-12\", \"M Expression To Suggest Variable Name\", each if [M Expression after Equal Sign] = null or [Is Parameter] then null else Replacer.ReplaceText(Variable_Rename_Suggestion_Template,\"{_M_CODE_}\",[M Expression after Equal Sign])),",
          "     // This piece of code is adding a new column named 'fnGetCommentVariableSuggestion' to the table. This new column is filled using the output of a function fnGetCommentVariableSuggestion, which is applied on each row in the column 'M Expression To Suggest Variable Name'. If any row in the 'M Expression To Suggest Variable Name' column is null, the corresponding row in the new column will also be null.",
          "    #\"Added Column with Comment Variable Suggestions-14\" = Table.AddColumn(#\"Added Column with Suggested Variable Names-13\", \"fnGetCommentVariableSuggestion\", each if [M Expression To Suggest Variable Name] = null then null else fnGetCommentVariableSuggestion([M Expression To Suggest Variable Name])),",
          "     // This code is adding a new column to the table returned by 'Call fnGetCommentVariableSuggestion'. It assigns a 'Suggested Variable Name' to each row. If the return value of 'fnGetCommentVariableSuggestion' is null, null is assigned, otherwise the suggested variable name is formed by concatenating a '#' with a range of text from 'fnGetCommentVariableSuggestion', excluding the last character, and hyphen, and the corresponding 'Line Index'.",
          "    #\"Added Suggested Variable Names Column-15\" = Table.AddColumn(#\"Added Column with Comment Variable Suggestions-14\", \"Suggested Variable Name\", each if [fnGetCommentVariableSuggestion] = null then null else \"#\" & Text.Range([fnGetCommentVariableSuggestion],0,Text.Length([fnGetCommentVariableSuggestion])-1) & \"-\" & Number.ToText([Line Index]) & \"\"\"\"),",
          "     // This code is filtering rows from the \"Added Custom\" table by only selecting those rows where the field \"Suggested Variable Name\" is not null and not an empty string.",
          "    #\"Filtered Rows With Non-Null And Non-Empty Values-16\" = Table.SelectRows(#\"Added Suggested Variable Names Column-15\", each [Suggested Variable Name] <> null and [Suggested Variable Name] <> \"\"),",
          "     // This code is selecting specific columns (\"M Expression Before Equal Sign\", \"Suggested Variable Name\", \"M Expression ID\") from the \"Filtered Rows\" table, and discarding the rest.",
          "    #\"Selected Necessary Columns-17\" = Table.SelectColumns(#\"Filtered Rows With Non-Null And Non-Empty Values-16\", {\"M Expression Before Equal Sign\", \"Suggested Variable Name\", \"M Expression ID\"}),",
          "     // ```This code is renaming two columns in a table to be more standardized. The \"M Expression Before Equal Sign\" column becomes \"Find\", and the \"Suggested Variable Name\" becomes \"Replace\".```",
          "    #\"Renamed Columns For Clarity-18\" = Table.RenameColumns(#\"Selected Necessary Columns-17\", {{\"M Expression Before Equal Sign\", \"Find\"}, {\"Suggested Variable Name\", \"Replace\"}}),",
          "     // This piece of code is transforming the column types for two columns, namely \"Replace\" and \"Find\", to text data type in the table that has had its column names standardized.",
          "    #\"Transformed Column Types to Text-19\" = Table.TransformColumnTypes(#\"Renamed Columns For Clarity-18\", {{\"Replace\", type text}, {\"Find\", type text}}),",
          "     // This piece of code is changing the data type of the column named \"M Expression ID\" to text in the table named #\"Transformed Column Types to Text-19\", and storing the output in a new table #\"Transformed Column Type to Text-20\".",
          "    #\"Transformed Column Type to Text-20\" = Table.TransformColumnTypes(#\"Transformed Column Types to Text-19\", {{\"M Expression ID\", type text}}),",
          "     // This code is replacing any errors found in the \"M Expression ID\" column of the \"Transform columns\" table with null values in Power Query.",
          "    #\"Replaced Error Values with Null in M Expression ID Column-21\" = Table.ReplaceErrorValues(#\"Transformed Column Type to Text-20\", {{\"M Expression ID\", null}})",
          "in",
          "    #\"Replaced Error Values with Null in M Expression ID Column-21\""
        ],
        "kind": "m",
        "lineageTag": "f87b49fb-776d-42e9-9287-8ef0f33b4fea",
        "queryGroup": "Dynamic Management View Queries "
      }
    ],
    "maxParallelismPerRefresh": 1,
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "description": "Extracts Power Query Code from a dataset.",
        "folder": "Dynamic Management View Queries "
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Parameters to support Power Query Extraction",
        "folder": "Parameters\\Power Query"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Parameters\\Azure Open AI"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Azure Open AI"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Functions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Functions\\Azure Open API"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "7"
          }
        ],
        "folder": "Output"
      }
    ],
    "relationships": [
      {
        "name": "bcafbe1f-6fc4-4846-b45c-e58ab4f5e731",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "M Expression ID",
        "fromTable": "Power Query Code",
        "toColumn": "M Expression ID",
        "toTable": "Power Query Code Transformed"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Power Query Code",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Dataset Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "793a0d0e-0dd1-4034-8a19-4eab90a93cca",
            "sourceColumn": "Dataset Name",
            "summarizeBy": "none"
          },
          {
            "name": "Table Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be3dace9-3ff6-4b06-bb4e-82d227bcce14",
            "sourceColumn": "Table Name",
            "summarizeBy": "none"
          },
          {
            "name": "M Expression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "325a3f32-0727-4767-b9eb-848e9c49e349",
            "sourceColumn": "M Expression",
            "summarizeBy": "none"
          },
          {
            "name": "Starts with Let",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "ee7bb702-b4b0-4f2e-b810-c0813252681d",
            "sourceColumn": "Starts with Let",
            "summarizeBy": "none"
          },
          {
            "name": "M Expression ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDefaultLabel": true,
            "lineageTag": "a1bc2a3a-a342-4aa4-b2be-cd428e19df49",
            "sourceColumn": "M Expression ID",
            "summarizeBy": "none"
          }
        ],
        "description": "Original Power Query Code",
        "lineageTag": "b957776b-58cd-4bfe-b714-59b4e48cb492",
        "partitions": [
          {
            "name": "Power Query Code",
            "mode": "import",
            "queryGroup": "Output",
            "source": {
              "expression": [
                "/*let",
                "    Source = Table.Combine({#\"M Expressions Not Loaded into Dataset\", #\"M Expressions Visible in Dataset\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(Source, \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Index\", \"M Expression ID\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each if Is_Dev = true then ([Table Name] = \"WebURL\" or [Table Name] = \"AlignmentDim\") else 1=1),",
                "    #\"Fix Source Issue\" = Table.ReplaceValue(#\"Filtered Rows\",\"Source =\",\"#\"\"Source\"\" =\",Replacer.ReplaceText,{\"M Expression\"}),",
                "    #\"Fix Source Issue 2\" = Table.ReplaceValue(#\"Fix Source Issue\",\"(Source,\",\"(#\"\"Source\"\",\",Replacer.ReplaceText,{\"M Expression\"})",
                "in",
                "    #\"Fix Source Issue 2\"*/",
                "",
                "let",
                "     // This code is combining two tables, \"M Expressions Not Loaded into Dataset\" and \"M Expressions Visible in Dataset\", into one new table titled \"Source\".",
                "    #\"Combined Not Loaded and Visible M Expressions Tables-1\" = Table.Combine({#\"M Expressions Not Loaded into Dataset\", #\"M Expressions Visible in Dataset\"}),",
                "     // This code adds an index column named \"Index\" starting with the value 1 to the input table \"Source\". The index increments by 1 for each subsequent row. The data type of the index is set as Int64.",
                "    #\"Added Index Column to Source Table-2\" = Table.AddIndexColumn(#\"Combined Not Loaded and Visible M Expressions Tables-1\", \"Index\", 1, 1, Int64.Type),",
                "     // This code is reordering the columns in the table \"Added Index\". The new order is specified as \"Index\", \"Dataset Name\", \"Table Name\", \"M Expression\", and \"Starts with Let\".",
                "    #\"Reordered Columns in Table-3\" = Table.ReorderColumns(#\"Added Index Column to Source Table-2\",{\"Index\", \"Dataset Name\", \"Table Name\", \"M Expression\", \"Starts with Let\"}),",
                "     // This line of code is renaming the \"Index\" column in the \"Reordered Columns\" table to \"M Expression ID\".",
                "    #\"Columns Renamed in Table-4\" = Table.RenameColumns(#\"Reordered Columns in Table-3\",{{\"Index\", \"M Expression ID\"}}),",
                "     // This piece of code is filtering rows from a renamed table. If the \"Is_Dev\" column is true, only rows with \"Table Name\" equal to \"WebURL\" or \"AlignmentDim\" are selected, else all rows are returned.",
                "    #\"Selected Rows Based on Dev Status and Table Name-5\" = Table.SelectRows(#\"Columns Renamed in Table-4\", each if Is_Dev = true then ([Table Name] = \"WebURL\" or [Table Name] = \"AlignmentDim\") else 1=1),",
                "     // This code is replacing the string \"#Source\" with \"#\"\"Source\"\"\" in the \"M Expression\" column of the \"Filtered Rows\" table. This resolves any issues stemming from the incorrect syntax in the source column name.",
                "    #\"Replaced Special Characters in Filtered Rows-6\" = Table.ReplaceValue(#\"Selected Rows Based on Dev Status and Table Name-5\",\"Source =\",\"#\"\"Source\"\" =\",Replacer.ReplaceText,{\"M Expression\"}),",
                "     // This code is addressing an issue within the data source by replacing a wrongly formatted string. Particularly, it is fixing incorrect quotation marks usage in column \"M Expression\" by changing '(\"Source\",' to '(\"Source\",'.",
                "    #\"Replaced Source Issue in Table-7\" = Table.ReplaceValue(#\"Replaced Special Characters in Filtered Rows-6\",\"(Source,\",\"(#\"\"Source\"\",\",Replacer.ReplaceText,{\"M Expression\"}),",
                "    // This code addresses Source being in the in statement at the end of the code",
                "    #\"Replaced Source Issue at the End-8\" = Table.ReplaceValue(#\"Replaced Source Issue in Table-7\",\"in#(lf)    Source\",\"in#(lf)    #\"\"Source\"\"\",Replacer.ReplaceText,{\"M Expression\"})",
                "in",
                "    #\"Replaced Source Issue at the End-8\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Power Query Code Transformed",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Table Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b67006d-f4c8-4131-8875-c4dd618058b6",
            "sourceColumn": "Table Name",
            "summarizeBy": "none"
          },
          {
            "name": "M Expression ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "c6b69a3c-ddd7-44b4-b211-1b752ea5a5d3",
            "sourceColumn": "M Expression ID",
            "summarizeBy": "none"
          },
          {
            "name": "M Expression with Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "348dfd45-27f6-4cbf-a291-bd96c7d30d7e",
            "sourceColumn": "M Expression with Comments",
            "summarizeBy": "none"
          },
          {
            "name": "M Expression with Comments and Variable Name Changes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f92ef062-d0c8-4926-a012-b0b673f6c8cc",
            "sourceColumn": "M Expression with Comments and Variable Name Changes",
            "summarizeBy": "none"
          }
        ],
        "description": "Power Query Code from the dataset(s) transformed by ChatGPT",
        "lineageTag": "131cfbe0-c3d3-4849-bb39-df10997955ff",
        "partitions": [
          {
            "name": "Power Query Code Transformed",
            "mode": "import",
            "queryGroup": "Output",
            "source": {
              "expression": [
                "/*let",
                "    Source = #\"M Expressions Parsed Commenting\",",
                "    #\"Grouped Rows\" = Table.Group(Source, {\"M Expression ID\", \"Table Name\"}, {{\"M Expression\", each Text.Combine([M Expression with Comment],\"#(lf)\"), type nullable text}}),",
                "    #\"Merge with Variable Naming for use in custom function\" = Table.NestedJoin(#\"Grouped Rows\", {\"M Expression ID\"}, #\"M Expressions Variable Naming\", {\"M Expression ID\"}, \"M Expression Variable Naming\", JoinKind.LeftOuter),",
                "    #\"Call Bulk Find and Replace\" = Table.AddColumn(#\"Merge with Variable Naming for use in custom function\", \"fnBulkReplace\", each fnBulkReplace([M Expression], [M Expression Variable Naming])),",
                "    #\"Expand to get updated code\" = Table.ExpandRecordColumn(#\"Call Bulk Find and Replace\", \"fnBulkReplace\", {\"Code\"}, {\"Code\"}),",
                "    #\"Added Code Derived\" = Table.TransformColumnTypes(Table.AddColumn(#\"Expand to get updated code\", \"Code Derived\", each try [Code] otherwise [M Expression]), {{\"Code Derived\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Code Derived\",{{\"M Expression\", \"M Expression with Comments\"}, {\"Code Derived\", \"M Expression with Comments and Variable Name Changes\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"M Expression with Comments and Variable Name Changes\", type text}, {\"Table Name\", type text}}),",
                "    #\"Removed other columns\" = Table.SelectColumns(#\"Changed Type\", {\"M Expression ID\", \"Table Name\", \"M Expression with Comments\", \"M Expression with Comments and Variable Name Changes\"})",
                "in",
                "    #\"Removed other columns\"*/",
                "let",
                "     // This line of code is assigning the table or query named \"M Expressions Parsed Commenting\" in the Power Query to the variable \"Source\".",
                "    #\"Expressions Parsed for Commenting-1\" = #\"M Expressions Parsed Commenting\",",
                "     // This code is grouping rows in the \"Source\" table by \"M Expression ID\" and \"Table Name\". For each group, it combines the \"M Expression with Comment\" into a single text string separated by line feeds. The result is assigned to a new column named \"M Expression\".",
                "    #\"Grouped Tables By M Expression ID and Table Name-2\" = Table.Group(#\"Expressions Parsed for Commenting-1\", {\"M Expression ID\", \"Table Name\"}, {{\"M Expression\", each Text.Combine([M Expression with Comment],\"#(lf)\"), type nullable text}}),",
                "     // This code is merging the \"Grouped Rows\" table with the \"M Expressions Variable Naming\" table based on the \"M Expression ID\" column. It uses a left outer join to include all records from \"Grouped Rows\" and matched records from the \"M Expressions Variable Naming\". The resulting table has an additional column \"M Expression Variable Naming\".```",
                "    #\"Joined Grouped Rows with M Expressions Variable Naming-3\" = Table.NestedJoin(#\"Grouped Tables By M Expression ID and Table Name-2\", {\"M Expression ID\"}, #\"M Expressions Variable Naming\", {\"M Expression ID\"}, \"M Expression Variable Naming\", JoinKind.LeftOuter),",
                "     // ```This piece of code is adding a new column named \"fnBulkReplace\" to the table called \"Merge with Variable Naming for use in custom function\". This is done by invoking the function fnBulkReplace for each row in the table, using the \"M Expression\" and \"M Expression Variable Naming\" columns as its parameters.```",
                "    #\"Added Column with Bulk Replace Function Results-4\" = Table.AddColumn(#\"Joined Grouped Rows with M Expressions Variable Naming-3\", \"fnBulkReplace\", each fnBulkReplace([M Expression], [M Expression Variable Naming])),",
                "     // This line of code is expanding a record column named \"fnBulkReplace\" in the table obtained from the \"Call Bulk Find and Replace\" step. The expansion is done to retrieve the \"Code\" property from within the record, and the retrieved property is placed in a new column named \"Code\".```",
                "    #\"Expanded Record Column in Bulk Find and Replace-5\" = Table.ExpandRecordColumn(#\"Added Column with Bulk Replace Function Results-4\", \"fnBulkReplace\", {\"Code\"}, {\"Code\"}),",
                "     // This code adds a new column \"Code Derived\" to the table. It tries to get the \"Code\" value, if it's not available, it retrieves the \"M Expression\" value instead. Then, it transforms the column's data type to text.",
                "    #\"Added and Transformed Derived Code Column-6\" = Table.TransformColumnTypes(Table.AddColumn(#\"Expanded Record Column in Bulk Find and Replace-5\", \"Code Derived\", each try [Code] otherwise [M Expression]), {{\"Code Derived\", type text}}),",
                "     // This code chunk is renaming two columns in a table: changing \"M Expression\" to \"M Expression with Comments\" and \"Code Derived\" to \"M Expression with Comments and Variable Name Changes\".",
                "    #\"Renamed Columns in Derived Code Table-7\" = Table.RenameColumns(#\"Added and Transformed Derived Code Column-6\",{{\"M Expression\", \"M Expression with Comments\"}, {\"Code Derived\", \"M Expression with Comments and Variable Name Changes\"}}),",
                "     // This code is transforming the data type of the columns \"M Expression with Comments and Variable Name Changes\" and \"Table Name\" to text in the table \"Renamed Columns\".```",
                "    #\"Transformed Column Types to Text-8\" = Table.TransformColumnTypes(#\"Renamed Columns in Derived Code Table-7\",{{\"M Expression with Comments and Variable Name Changes\", type text}, {\"Table Name\", type text}}),",
                "     // This code segment removes all columns from the #\"Transformed Column Types to Text-8\" table except for \"M Expression ID\", \"Table Name\", \"M Expression with Comments\", and \"M Expression with Comments and Variable Name Changes\".",
                "    #\"Selected Specific Columns from Changed Type Table-9\" = Table.SelectColumns(#\"Transformed Column Types to Text-8\", {\"M Expression ID\", \"Table Name\", \"M Expression with Comments\", \"M Expression with Comments and Variable Name Changes\"})",
                "in",
                "    #\"Selected Specific Columns from Changed Type Table-9\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Columns",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "27bd4c06f768465782b85666c93a204b"
          }
        ],
        "columns": [
          {
            "name": "Columns",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "075083d1-002c-46ae-8225-4d4c782a2cc9",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Columns Fields"
                }
              ]
            },
            "sortByColumn": "Columns Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Columns Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "418fa969-4a1a-40c1-8655-fe1b4faeeca7",
            "sortByColumn": "Columns Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Columns Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "2b7d58d0-5dc1-462e-bfa4-d73189ab14b1",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "982c0368-b9b3-4861-95be-40a4d9070140",
        "partitions": [
          {
            "name": "Columns",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Additional Comments\", NAMEOF('Power Query Code Transformed'[M Expression with Comments]), 0),",
                "    (\"Additional Comments & Variable Name Changes\", NAMEOF('Power Query Code Transformed'[M Expression with Comments and Variable Name Changes]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}